services:
  #Database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  productdb:
    image: mysql:8.0.29

  customerdb:
    image: postgres:alpine3.16

  basketdb:
    image: redis:alpine3.16

  inventorydb:
    image: mongo

  #Infrastructure section
  rabbitmq: 
    image: rabbitmq:3-management-alpine
  
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
  #miroservices api section
  product.api:
    image: ${DOCKER_REGISTRY-}product.api:${PLATFORM:-linux}-${TAG-lastest}
    build:
      context: .
      dockerfile: Services/Product.API/Dockerfile
    
#Network section
networks:
  default:
    name: ercommerce_network
    driver: bridge

# Volume section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
  postgres_data:
    name: posgres_data
  portainer_data:
    name: portainer_data
  elasticsearch_data:
    name: elasticsearch_data
  jeager_data:
    name: jeager_data
  mongo_data:
    name: mongo_data
  pgadmin_data:
    name: pgadmin_data

